flowchart LR
  subgraph CanvasApps
  end
  subgraph Screens
  end
  subgraph Workflows
    W1["EndFormFlow (EndFormFlow-82921763-2342-F011-8779-000D3A0CEB69)"]
    W2["EndFormFlowReminder (EndFormFlowReminder-128F82AA-B942-F011-877A-000D3A0CEB69)"]
    W3["IdentifierReminderFlow (IdentifierReminderFlow-D4AE74B0-DA42-F011-877A-000D3A0CEB69)"]
    W4["PeopleListFlow (PeopleListFlow-3CE0853C-4C36-F011-8C4C-6045BD0ACADB)"]
    W5["PMflow (PMflow-A3194D5E-D434-F011-8C4C-6045BD0ACADB)"]
    W6["PMFormReminderFlow (PMFormReminderFlow-B025C04D-D342-F011-877A-000D3A0CEB69)"]
    W7["ReplybraryDailyPipedrivecheck (ReplybraryDailyPipedrivecheck-5898F434-A147-F011-8779-000D3A0CEB69)"]
    W8["Replybrary_GetExchangeRate (Replybrary_GetExchangeRate-4E437A2B-C74D-F011-877B-000D3A0CEB69)"]
    W9["Replybrary_Identifier_Flow (Replybrary_Identifier_Flow-38CA161E-BA34-F011-8C4C-6045BD0ACADB)"]
    W10["UploadLogo (UploadLogo-F9309D25-C742-F011-877A-000D3A0CEB69)"]
  end
  subgraph Connectors
    C1["shared_office365groups"]
    C2["shared_office365users"]
    C3["shared_sharepointonline"]
    C4["shared_teams"]
  end
  subgraph EnvironmentVariables
    E1["App Link (wmreply_Replybrary_App_Link)"]
    E2["Client List (wmreply_Replybrary_Client_List)"]
    E3["Currency List (wmreply_Replybrary_Currency_List)"]
    E4["M365 Group ID (wmreply_Replybrary_M365GroupID)"]
    E5["People List (wmreply_Replybrary_People_List)"]
    E6["Projects List (wmreply_Replybrary_Project_List)"]
    E7["SharePoint Site URL (wmreply_Replybrary_SP_Site)"]
  end

  W1 --> C3
  W1 --> C4
  W1 --> E1
  W1 --> E6
  W1 --> E7
  W2 --> C3
  W2 --> C4
  W2 --> E1
  W2 --> E6
  W2 --> E7
  W3 --> C3
  W3 --> C4
  W3 --> E1
  W3 --> E6
  W3 --> E7
  W4 --> C1
  W4 --> C2
  W4 --> C3
  W4 --> E4
  W4 --> E5
  W4 --> E7
  W5 --> C4
  W5 --> E1
  W6 --> C3
  W6 --> C4
  W6 --> E1
  W6 --> E6
  W6 --> E7
  W7 --> C2
  W7 --> C3
  W7 --> E5
  W7 --> E6
  W7 --> E7
  W8 --> C3
  W8 --> E3
  W8 --> E7
  W9 --> C3
  W9 --> C4
  W9 --> E1
  W9 --> E6
  W9 --> E7
  W10 --> C3
  W10 --> E2
  W10 --> E7
